# Generated by Django 2.0.6 on 2018-06-25 06:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
